equipment_profile:

  access_control: true
  firewall: false

  partitioning: |
    clearpart --all --initlabel
    part /boot --fstype=ext4 --size=1024
    part / --fstype=ext4 --size=60000
    part /home --fstype=ext4 --size=4096 --grow

  operating_system:
    distribution: centos
    distribution_major_version: 7
    distribution_version: 7.6

  equipment_type: server

  configuration:
    keyboard_layout: us
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: x86_64

