---
- name: include_vars ░ Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags:
    - always

- name: include_tasks ░ Use OS dedicated firewall task
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "firewall/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "firewall/{{ ansible_facts.os_family | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "firewall/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "firewall/{{ ansible_facts.os_family | replace(' ','_') }}.yml"
      skip: true
  tags:
    - internal
    - firewall

- name: "package █ Install {{ log_server_packages_to_install }} packages"
  package:
    name: "{{ log_server_packages_to_install }}"
    state: present
  tags:
    - package

- name: file █ Create /var/log/rsyslog directory
  file:  # noqa 208
    path: /var/log/rsyslog
    setype: var_log_t
    state: directory
    recurse: yes
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.selinux.status == "enabled"

- name: "template █ Generate {{ log_server_rsyslog_conf_path }}"
  template:
    src: rsyslog.conf.j2
    dest: "{{ log_server_rsyslog_custom_conf_path | default(log_server_rsyslog_conf_path) }}"
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart rsyslog service
  tags:
    - template

- name: seport █ Allow syslog port into SELinux
  seport:
    ports: "{{ log_server_port }}"
    proto: "{{ item }}"
    setype: syslogd_port_t
    state: present
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.selinux.status == "enabled"
  loop:
    - tcp
    - udp
  notify: service █ Restart rsyslog service

- name: "template █ Generate /etc/logrotate.d/rsyslog"
  template:
    src: rsyslog_logrotate.j2
    dest: /etc/logrotate.d/rsyslog
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart rsyslog service
  tags:
    - template

- name: lineinfile █ Configure logrotate to use xz
  lineinfile:
    path: /etc/logrotate.conf
    regexp: "{{ item }}"
    line: "{{ item }}"
  loop:
    - compresscmd /usr/bin/xz
    - uncompresscmd /usr/bin/unxz
    - compressext .xz
  notify: service █ Restart rsyslog service
  tags:
    - template

- name: meta █ Run handler tasks to restart rsyslog services
  meta: flush_handlers

- name: "service █ Manage {{ log_server_services_to_start }} services state"
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ log_server_services_to_start }}"
  tags:
    - service
