---
- name: Verify
  hosts: all
  tasks:

    - name: Collect package facts
      package_facts:
        manager: auto

    - name: Collect services facts
      service_facts:

    - name: Assert common packages are installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      loop:
        - conman
        - ipmitool

    - name: Assert needed el7 conman packages are installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      loop:
        - libselinux-python
        - policycoreutils-python
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "7"

    - name: Assert needed el8 conman packages are installed
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      loop:
        - python3-libselinux
        - python3-policycoreutils
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "8"

    - name: Retrieve file /etc/conman.conf system status
      stat:
        path: /etc/conman.conf
      register: reg_file_conman
      changed_when: false

    - name: Assert file /etc/conman.conf exists
      assert:
        that:
          - reg_file_conman.stat.exists
          - reg_file_conman.stat.mode == '0644'
          - reg_file_conman.stat.pw_name == 'root'
          - reg_file_conman.stat.gr_name == 'root'

    - name: Retrieve client configuration in /etc/conman.conf file
      lineinfile:
        path: /etc/conman.conf
        regexp: 'console name="instance" dev="ipmitool.exp 10.10.102.1 ADMIN ADMIN"'
        state: absent
      check_mode: yes
      register: reg_conf_conman
      changed_when: false

    - name: Check /etc/conman.conf file contains console configuration for expected client
      assert:
        that: reg_conf_conman.found

    - name: Retrieve file /var/log/conman/instance.log system status
      stat:
        path: /etc/conman.conf
      register: reg_log_conman
      changed_when: false

    - name: Assert log client file /var/log/conman/instance.log exists
      assert:
        that: reg_log_conman.stat.exists


    - name: Retrieve dir system status
      stat:
        path: /usr/share/conman/exec
      register: reg_dir_conman
      changed_when: false
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "7"

    - name: Assert dir conman_execpath /usr/share/conman/exec exist
      assert:
        that:
          - reg_dir_conman.stat.exists
          - reg_dir_conman.stat.isdir
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "7"

    - name: Retrieve dir system status
      stat:
        path: /usr/lib/conman/exec
      register: reg_dir_conman
      changed_when: false
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "8"

    - name: Assert dir conman_execpath /usr/lib/conman/exec exist
      assert:
        that:
          - reg_dir_conman.stat.exists
          - reg_dir_conman.stat.isdir
      when:
        - ansible_facts.os_family == "RedHat"
        - ansible_facts.distribution_major_version == "8"

    - name: Check conman is enabled
      assert:
        that: "ansible_facts.services['conman.service'].status == 'enabled'"

    - name: Check conman is running
      assert:
        that: "ansible_facts.services['conman.service'].state == 'running'"
