---
- name: systemd █ Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: service █ Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)

