equipment_profile:

  access_control: false
  firewall: false

  console: console=tty0 console=ttyS1,115200n8
  kernel_parameters:

  partitioning: |
    d-i partman-auto/disk string /dev/sda
    d-i partman-auto/method string regular
    d-i partman-auto/choose_recipe select atomic
    d-i partman-auto/init_automatically_partition select Guided - use entire disk

  operating_system:
    distribution: ubuntu
    distribution_major_version: 18
    distribution_version: 18.04

  equipment_type: server

  configuration:
    keyboard_layout: fr
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: x86_64
      cores: 64
