---

- name: group █ Add users groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ users_basic.users }}"

- name: user █ Add/remove users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid }}"
    group: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    password: "{{ item.password }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(omit) }}"
    remove: "{{ item.remove | default('no') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ users_basic.users }}"

- name: authorized_key █ Manage user authorized_keys if exist
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
    exclusive: "{{ item.ssh_key_exclusive | default(omit) }}"
  with_items: "{{ users_basic.users }}"
  when: item.ssh_key is defined and item.ssh_key
