---
nfs_client_packages_to_install:
  - nfs-utils
  - python3-libselinux
  - python3-policycoreutils
nfs_server_packages_to_install:
  - nfs-utils
nfs_server_services_to_start:
  - nfs-server
  - rpcbind
nfs_server_firewall_services_to_add:
  - nfs
  - rpc-bind
  - mountd
