---
# Should role create directories to be exported if not exist?
nfs_server_create_directories_if_not_exist: true

# What should be the client mount state?
# To see possible values refer to https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html#parameter-state
nfs_client_directories_state: mounted

# For SELinux based distributions (RHEL), booleans to enable on client
nfs_client_sebooleans:
  - use_nfs_home_dirs
  - httpd_use_nfs

nfs_profile: []

