---
- name: group █ Add karma group
  ansible.builtin.group:
    name: karma
    gid: "{{ prometheus_server_karma_user_gid }}"
    state: present

- name: user █ Add karma user
  ansible.builtin.user:
    name: karma
    shell: /bin/false
    uid: "{{ prometheus_server_karma_user_uid }}"
    group: karma
    home: /var/lib/karma
    state: present

- name: Package █ Install karma package
  ansible.builtin.package:
    name: "{{ prometheus_server_karma_packages_to_install }}"
    state: present
  tags:
    - package

- name: template █ Generate karma service file
  ansible.builtin.template:
    src: karma.service.j2
    dest: /etc/systemd/system/karma.service
    owner: root
    group: root
    mode: 0755
  notify: systemd █ Reload systemd configuration
  tags:
    - template

- name: file █ Create karma directories structure
  ansible.builtin.file:
   path: "{{ item }}"
   state: directory
   mode: 0750
   owner: karma
   group: karma
  loop:
   - /etc/karma/

- name: Template █ Generate /etc/karma/karma.yml
  ansible.builtin.template:
    src: karma.yml.j2
    dest: /etc/karma/karma.yml
    owner: karma
    group: karma
    mode: 0640
  notify: service █ Restart karma service
  tags:
    - template

- meta: flush_handlers

- name: service █ Manage karma service state
  ansible.builtin.service:
    name: karma
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
