---
- name: include_vars ░ Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags:
    - always

- name: "package █ Install {{ http_server_packages_to_install | join(' ') }} packages"
  ansible.builtin.package:
    name: "{{ http_server_packages_to_install }}"
    state: present
  tags:
    - package

- name: include_tasks ░ Use OS dedicated firewall task
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_version }}/firewall.yml"
        - "{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}/firewall.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}_{{ ansible_facts.distribution_version }}/firewall.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}/firewall.yml"
        - "{{ ansible_facts.distribution | replace(' ','_') }}/firewall.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}/firewall.yml"
      skip: true
  tags:
    - internal
    - firewall

- name: include_tasks ░ Use OS dedicated task
  ansible.builtin.include_tasks: "{{ outer_item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_version }}/main.yml"
        - "{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}/main.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}_{{ ansible_facts.distribution_version }}/main.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}/main.yml"
        - "{{ ansible_facts.distribution | replace(' ','_') }}/main.yml"
        - "{{ ansible_facts.os_family | replace(' ','_') }}/main.yml"
      skip: true
  loop_control:
    loop_var: outer_item
  tags:
    - internal

- name: lineinfile █ Set http server main settings
  ansible.builtin.lineinfile:
    path: "{{ pxe_stack_apache_main_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ litem.line }}"
  with_items: "{{ http_server_settings }}"
  when:
    - http_server_settings is not none
    - http_server_settings is iterable
  notify: service █ Restart http server service

- name: template █ Generate http server configuration files
  ansible.builtin.template:
    src: custom.conf.j2
    dest: "{{ pxe_stack_apache_conf_path }}/{{ item.rule_name }}.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - template
  with_items: "{{ http_server_configurations_files }}"
  when:
    - http_server_configurations_files is not none
    - http_server_configurations_files is iterable
  notify: service █ Restart http server service

- name: apache2_module █ Enable apache2 modules
  community.general.apache2_module:
    force: "{{ item.force | default(omit, true) }}"
    identifier: "{{ item.identifier | default(omit, true) }}"
    ignore_configcheck: "{{ item.ignore_configcheck | default(omit, true) }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit, true) }}"
  with_items: "{{ http_server_modules }}"
  when:
    - http_server_modules is not none
    - http_server_modules is iterable
    - item.name is defined and item.name is not none
  notify: service █ Restart http server service

- name: "service █ Manage {{ http_server_services_to_start | join(' ') }} state"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "{{ (http_server_enable_services | default(bb_enable_services) | default(true, true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (http_server_start_services | default(bb_start_services) | default(true, true) | bool) | ternary('started', omit) }}"
  loop: "{{ http_server_services_to_start }}"
  tags:
    - service
