---
rsyslog_packages_to_install:
  - rsyslog
  - logrotate
  - xz
rsyslog_services_to_start:
  - rsyslog
rsyslog_conf_path: /etc/rsyslog.conf
rsyslog_client_rsyslog_conf_path: /etc/rsyslog.d/client.conf
rsyslog_server_rsyslog_conf_path: /etc/rsyslog.d/server.conf
rsyslog_firewall_services_to_add:
  - syslog
rsyslog_work_dir: /var/spool/rsyslog
