---
- name: service <|> Restart powerman
  ansible.builtin.service:
    name: powerman
    state: "{{ (powerman_start_services | default(bb_start_services) | default(true) | bool) | ternary('restarted', omit) }}"
  when:
    - "'service' not in ansible_skip_tags"
    - powerman_start_services | default(bb_start_services) | default(true)
