---
- name: service <|> Restart powerman
  ansible.builtin.service:
    name: powerman
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - powerman_start_services | default(bb_start_services) | default(true) | bool
