---
log_server_RedHat_8:
  packages_to_install:
    - rsyslog
    - logrotate
    - xz
    - python3-libselinux
    - python3-policycoreutils
  services_to_start:
    - rsyslog
  firewall_services_to_add:
    - syslog
    - rsh # 514/tcp
