- name: "firewalld <|> Add services to firewall's zone"
  ansible.posix.firewalld:
    zone: "{{ rsyslog_firewall_zone | default(bb_services_firewall_zone, true) | default('public') }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - os_firewall | default(false) | bool
  loop: "{{ rsyslog_firewall_services_to_add }}"
  tags:
    - firewall

- name: "firewalld <|> Add custom port to firewall's zone"
  ansible.posix.firewalld:
    zone: "{{ rsyslog_firewall_zone | default(bb_services_firewall_zone, true) | default('public') }}"
    port: "{{ rsyslog_port }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - os_firewall | default(false) | bool
  tags:
    - firewall
