---
- name: Prepare
  hosts: management1
  tasks:
    - name: Install firewall package
      package:
        name: firewalld
        state: present

    - name: Start firewall
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: "Configure BlueBanquise repository"
      yum_repository:
        name: bluebanquise
        description: BlueBanquise 1.3 repository
        baseurl: https://bluebanquise.com/repository/releases/1.3/el$releasever/$basearch/bluebanquise/
        gpgcheck: False
      when: ansible_facts.os_family == "RedHat"
