---
- name: set_fact ░ Set static baseurl prefix
  set_fact:
    baseurl_prefix:
      "http://{{ networks[j2_node_main_network]['services_ip']['repository_ip'] }}/repositories/\
      {{ ep_operating_system['repositories_environment'] | default('') }}/\
      {{ ep_operating_system['distribution'] }}/\
      {{ ep_operating_system['distribution_version'] | default(ep_operating_system['distribution_major_version']) }}/\
      {{ ansible_architecture }}/"

- name: apt_repository █ Setting deb repositories
  apt_repository:
    repo: "{{ item.repo | default('deb [trusted=yes] ' + baseurl_prefix + ( item.name | default(item) | string ) + ' ' + ( item.distribution | default('./') )) }}"
    state: "{{ item.state | default('present') }}"
    update_cache: no
  with_items: "{{ repositories | union(external_repositories|default([])) }}"
  notify: command █ apt update cache

