---
pxe_stack_enable_cloning: false
pxe_stack_sshd_force_permitrootlogin: true

pxe_stack_ubuntu_preseed_preserve_sources_list: true
pxe_stack_ubuntu_user_data_preserve_sources_list: true
pxe_stack_ubuntu_user_data_enable_sudo: true
pxe_stack_ubuntu_user_data_sudo_user: bluebanquise

pxe_stack_client_os_redhat: true
pxe_stack_client_os_ubuntu: true
pxe_stack_client_os_dgx: false
pxe_stack_client_os_suse: true
