---
# Enable distributions support
pxe_stack_client_os_redhat: true
pxe_stack_client_os_ubuntu: true
pxe_stack_client_os_dgx: false
pxe_stack_client_os_suse: true

# Add cloning entry in ixpe menu
pxe_stack_enable_cloning: false

# Enable root user as default user
pxe_stack_enable_root: false
# Sudo user if root not enabled
pxe_stack_sudo_user: bluebanquise
# Set sudo user as passwordless sudoer
pxe_stack_sudo_is_passwordless: true

# Preserve default sources list for Ubuntu
pxe_stack_ubuntu_preserve_sources_list: true

# Preserve default sources list for OpenSUSE
pxe_stack_opensuse_preserve_sources_list: true
