parted:
  - device: /tmp/1g.img
    number: 1
    state: present
    flags: [ lvm ]
    part_end: "100%"

lvm:
  vgs:
    - vg: data
      pvs:
        - /dev/loop3p1
  lvs:
    - lv: data1
      size: 200M
      vg: data
    - lv: data2
      size: 300M
      vg: data

filesystem:
  - fstype: ext4
    dev: /dev/mapper/data-data1

mount:
  - path: /mnt/
    src: /dev/mapper/data-data1
    state: present
    fstype: ext4
