equipment_profile:

  access_control: true
  firewall: true

  console: console=tty0 console=ttyS1,115200n8
  kernel_parameters: nomodeset

  operating_system:
    distribution: centos
    distribution_major_version: 8

  equipment_type: server

  configuration:
    keyboard_layout: fr
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: x86_64
      cores: 24

