---
- name: plugins <|> Check which plugins are installed
  ansible.builtin.find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: grafana_installed_plugins

- name: plugins <|> Install plugins
  become: true
  ansible.builtin.command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  loop: "{{ grafana_plugins | difference(grafana_installed_plugins.files) | flatten(levels=1) }}"
  register: grafana_plugin_install
  until: grafana_plugin_install is succeeded
  retries: 5
  delay: 2
  notify:
    - restart grafana
