---
- name: package █ Install freeipmi and powerman
  ansible.builtin.package:
    name:
      - freeipmi
      - powerman
      - bluebanquise-filters
    state: present
  tags:
    - package

- name: template █ Generate /etc/powerman/powerman.conf
  ansible.builtin.template:
    src: powerman.conf.j2
    dest: /etc/powerman/powerman.conf
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart powerman
  tags:
    - template

- name: meta █ Run handler tasks to restart powerman service
  ansible.builtin.meta: flush_handlers

- name: service █ Manage powerman state
  ansible.builtin.service:
    name: powerman
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
