---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Check that files exists
    stat:
      path: "{{ item }}"
    register: stat_results
    with_items:
      - /usr/bin/free_root_disk
      - /root/.screenrc
      - /root/.vimrc
      - /root/.bashrc

  - name: assert files exist
    assert:
      that: "{{ item }}.stat.exists"
    loop: "{{ stat_results.results }}"
