role_version: 1.0.2

packages_to_install:
  ubuntu:
    _18:
      - chrony
  redhat:
    _7:
      - chrony
    _8:
      - chrony
  centos:
    _7:
      - chrony
    _8:
      - chrony

services_to_start:
  ubuntu:
    _18:
      - chronyd
  redhat:
    _7:
      - chronyd
    _8:
      - chronyd
  centos:
    _7:
      - chronyd
    _8:
      - chronyd

chrony_conf_path:
  ubuntu:
    _18: /etc/chrony/chrony.conf
  redhat:
    _7: /etc/chrony.conf
    _8: /etc/chrony.conf
  centos:
    _7: /etc/chrony.conf
    _8: /etc/chrony.conf


