---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: server-ext-pool
    groups:
      - server
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: server-ext-servers
    groups:
      - server
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: client-ext-pool
    groups:
      - client
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: client-ext-servers
    groups:
      - client
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: client-single-source
    groups:
      - client
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: client-multi-sources
    groups:
      - client
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: client-no-start
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      server:
        start_services: true
        time_chronyd_options: "-x"
        time_profile: server
      client:
        start_services: true
        time_chronyd_options: "-x"
        time_profile: client
    host_vars:
      server-ext-pool:
        network_interfaces:
          - interface: en0
            network: ice1-1
        external_time:
          time_server:
            pool:
              - pool.ntp.org
      server-ext-servers:
        network_interfaces:
          - interface: en0
            network: ice1-1
        external_time:
          time_server:
            server:
              - 0.pool.ntp.org
              - 1.pool.ntp.org
              - 2.pool.ntp.org
      client-ext-pool:
        j2_node_main_network: ice1-1
        external_time:
          time_client:
            pool:
              - pool.ntp.org
      client-ext-servers:
        j2_node_main_network: ice2-1
        external_time:
          time_client:
            server:
              - 0.pool.ntp.org
              - 1.pool.ntp.org
              - 2.pool.ntp.org
      client-single-source:
        j2_node_main_network: ice1-1
      client-multi-sources:
        j2_node_main_network: ice2-1
      client-no-start:
        j2_node_main_network: ice1-1
        start_services: false
        time_profile: client
verifier:
  name: ansible
