---
- name: "firewalld â–ˆ Add ports to firewall's {{ slurm_firewall_zone | default('public') }} zone"
  firewalld:
    zone: "{{ slurm_firewall_zone | default('public') }}"
    port: "{{ item }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  loop:
    - "{{ slurm_SrunPortRange }}"
  tags:
    - firewall

