networks:
  ice2-1:
    subnet: 10.12.0.0
    prefix: 16
    netmask: 255.255.0.0
    broadcast: 10.12.255.255
    dhcp_unknown_range: 10.12.254.1 10.12.254.254
    gateway: 10.12.2.1
    is_in_dhcp: true
    is_in_dns: true
    services_ip:
      pxe_ip: 10.12.0.1
      ntp_ip: 10.12.0.1
      dns_ip: 10.12.0.1
      repository_ip: 10.12.0.1
      authentication_ip: 10.12.0.1
      time_ip: 10.12.0.1
      log_ip: 10.12.0.1
