---
- name: Prepare
  hosts: all
  tasks:
    - name: Install needed packages
      package:
        name: "{{ item }}"
        state: present
      when: ansible_facts.os_family == "RedHat"
      loop:
        - firewalld

    - name: Start needed services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      when: ansible_facts.os_family == "RedHat"
      loop:
        - firewalld

    - name: "Configure BlueBanquise repository"
      yum_repository:
        name: bluebanquise
        description: BlueBanquise 1.3 repository
        baseurl: https://bluebanquise.com/repository/releases/1.3/el$releasever/$basearch/bluebanquise/
        gpgcheck: False
      when: ansible_facts.os_family == "RedHat"
