---
### Lease times ###
# Consider increasing these values once cluster is in production.
dhcp_server_default_lease_time: 600
dhcp_server_max_lease_time: 7200

### iPXE Rom settings ###
# These default should suits most hardware.
# Refer to main documentation for possible values.
# It is possible using these settings to bind to an non BlueBanquise iPXE Rom.
dhcp_server_ipxe_driver: snponly
dhcp_server_ipxe_embed: dhcpretry

### Enable and/or start services ###
# These values can be set in inventory to manipulate
# services behavior. If not set, default to true for both.
# Roles variables precedence global ones:
# dhcp_server_start_services > bb_start_services > default(true)
# dhcp_server_enable_services > bb_enable_services > default(true)

# dhcp_server_start_services:
# dhcp_server_enable_services:

### Others ###
# Domain name provided by dhcp to clients
dhcp_server_domain_name:

# Specific settings
# Consider setting to true if using match patterns
dhcp_server_ignore_client_uids: false
dhcp_server_stash_agent_options: false

# Add user custom global settings to main dhcp configuration file
# No need to add ";" at the end, template will add it
dhcp_server_global_settings: []
dhcp_server_enable_patterns: false
