---
dns_server_packages_to_install:
  - bind9
  - python-netaddr
dns_server_services_to_start:
  - bind9
dns_server_dump_file: /var/named/data/cache_dump.db
dns_server_localhost_file: /var/named/named.localhost
dns_server_log_dir: data
dns_server_loopback_file: /var/named/named.loopback
dns_server_managed_keys_dir: /var/named/dynamic
dns_server_mem_stats_file: /var/named/data/named_mem_stats.txt
dns_server_named_dir: /etc/named
dns_server_root_hint_file: named.ca
dns_server_root_key_file: /etc/named.root.key
dns_server_statistics_file: /var/named/data/named_stats.txt
dns_server_var_dir: /var/named
dns_server_dns_user: bind
