---
- name: managements playbook
  hosts: "mg_managements"
  roles:

    - role: bluebanquise.infrastructure.set_hostname
      tags: set_hostname
    - role: bluebanquise.infrastructure.nic
      tags: nic
    - role: bluebanquise.infrastructure.http_server
      tags: http_server
    - role: bluebanquise.infrastructure.repositories
      tags: repositories
    - role: bluebanquise.infrastructure.hosts_file
      tags: hosts_file
    - role: bluebanquise.infrastructure.ssh_client
      tags: ssh_client
    - role: bluebanquise.infrastructure.dhcp_server
      tags: dhcp_server
    - role: bluebanquise.infrastructure.dns_server
      tags: dns_server
    - role: bluebanquise.infrastructure.time
      tags: time
      vars:
        time_profile: server
    - role: bluebanquise.infrastructure.pxe_stack
      tags: pxe_stack

