os_operating_system:
  distribution: "debian"
  distribution_version: "12"
  distribution_major_version: "12"

os_partitioning: "d-i partman-auto/disk string /dev/vda\nd-i partman-auto/method string regular\nd-i partman-auto/choose_recipe select atomic\nd-i partman-auto/init_automatically_partition select Guided - use entire disk\n"
