---
slurm_cluster_name: bluebanquise

## Computes configuration way to use (configfull vs configless)
slurm_computes_config: configfull

## files path
slurm_statesavelocation: /var/spool/slurmd/statesave
slurm_slurmdspooldir: /var/spool/slurmd/slurmd
slurm_slurmctldpidfile: /var/run/slurmctld.pid
slurm_slurmdpidfile: /var/run/slurmd.pid

## firewall and ports
slurm_firewall_zone: public
slurm_slurmtld_port: 6817
slurm_slurmd_port: 6818
slurm_slurmdbd_port: 6819
slurm_srunportrange: 60001-63000

## logging
slurm_slurmctlddebug: 5
slurm_slurmctldlogfile: /var/log/slurm/slurmctld.log
slurm_slurmddebug: 5
slurm_slurmdlogfile: /var/log/slurm/slurmd.log
slurm_slurmdbddebug: 5
slurm_slurmdbdlogfile: /var/log/slurm/slurmdbd.log

## timeouts
slurm_slurmctldtimeout: 600
slurm_slurmdtimeout: 600

## Accounting (storage)
slurm_enable_accounting: false
slurm_storageuser: slurm
slurm_storagepass: ssap_slurm
### mariadb
slurm_innodb_buffer_pool_size: 1024M
slurm_innodb_log_file_size: 64M
slurm_innodb_lock_wait_timeout: 900

## Other
slurm_returntoservice: 0
slurm_schedulertype: sched/backfill
slurm_selecttype: select/linear
slurm_mpidefault: pmi2
# additional slurm.conf go here
# slurm_slurm_conf_additional_content:
#   - tmpfs=/scratch
#   - AccountingstorageEnforce=associations

## Munge

# slurm_munge_key_b64: # User need to define it, would be too risky to provide one
