equipment_profile:

  access_control: false
  firewall: false

  console: console=tty0 console=ttyS1,115200n8
  kernel_parameters:

  partitioning: |
    clearpart --all --drives=sda
    part /boot --fstype="ext4" --ondisk=sda --size=1024
    part / --fstype="ext4" --ondisk=sda --size=10000 --grow

  operating_system:
    distribution: centos
    distribution_major_version: 8
    distribution_version: 8.0

  equipment_type: server

  configuration:
    keyboard_layout: fr
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: x86_64
      cores: 64
