##### RedHat os familly

- name: "copy █ Copy osdeploy files {{ pxe_stack_htdocs_path }}/osdeploy/"
  ansible.builtin.copy:
    src: osdeploy/redhat_{{ item.major }}.ipxe
    dest: "{{ pxe_stack_htdocs_path }}/osdeploy/redhat_{{ item.major }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_group }}"
  loop: "{{ pxe_stack_supported_os.redhat }}"

- name: file █ Generate links for all supported OS
  ansible.builtin.file:
    src: redhat_{{ item.0.major }}.ipxe
    dest: "{{ pxe_stack_htdocs_path }}/osdeploy/{{ item.1 }}_{{ item.0.major }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_group }}"
    state: link
    force: yes
  loop: "{{ pxe_stack_supported_os.redhat | subelements('distributions') }}"
  when: item.1 != 'redhat'

- name: "template █ Generate kickstarts {{ pxe_stack_htdocs_path }}/equipment_profiles/{item}.kickstart.cfg"
  ansible.builtin.template:
    src: "RedHat/kickstart.cfg.j2"
    dest: "{{ pxe_stack_htdocs_path }}/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.kickstart.cfg"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_group }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['ep_equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['ep_operating_system']['distribution']|lower) in ['redhat','centos','rockylinux','cloudlinux','oraclelinux','almalinux']
  tags:
    - template

- name: "template █ Generate equipment_profiles {{ pxe_stack_htdocs_path }}/equipment_profiles/{item}.ipxe"
  ansible.builtin.template:
    src: "RedHat/equipment_profile_ks.ipxe.j2"
    dest: "{{ pxe_stack_htdocs_path }}/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_group }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['ep_equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['ep_operating_system']['distribution']|lower) in ['redhat','centos','rockylinux','cloudlinux','oraclelinux','almalinux']
  tags:
    - template
