---
slurm_home_path: /etc/slurm
slurm_mysql_cnf_dir: /etc/my.cnf.d
slurm_packages_to_install:
  controller:
    - munge
    - munge-libs
    - slurm
    - slurm-devel
    - slurm-slurmctld
  accounting:
    - mariadb
    - mariadb-server
    - python3-mysqlclient
    - slurm-slurmdbd
  compute:
    - munge
    - munge-libs
    - slurm
    - slurm-devel
    - slurm-slurmd
  submitter:
    - munge
    - munge-libs
    - slurm
    - slurm-devel
