## Tested on OracleLinux_8.yml 8.0
---
- name: sefcontext â–ˆ Set SELinux context on /var/www/html/preboot_execution_environment/nodes
  sefcontext:
    target: '/var/www/html/preboot_execution_environment/nodes(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  when:
    - ansible_facts.selinux.status == "enabled"
