---
- name: systemd <|> Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - "'service' not in ansible_skip_tags"

- name: service <|> Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - slurm_start_services | default(bb_start_services) | default(true) | bool

- name: Run scontrol reconfigure
  ansible.builtin.command:
    cmd: scontrol reconfigure
  changed_when: true
