equipment_profile:

  access_control: false # Selinux, AppArmor, etc. Selinux: true = enforcing, false = disabled
  firewall: false # Enable or disable native firewall

  partitioning: | # Please provide native distribution partitioning
    d-i partman-auto/disk string /dev/sda
    d-i partman-auto/method string regular
    d-i partman-auto/choose_recipe select atomic
    d-i partman-auto/init_automatically_partition select Guided - use entire disk

  operating_system:
    distribution: ubuntu # centos, ubuntu, opensuse
    distribution_major_version: 18.04
    distribution_version: 18.04

  equipment_type: server # If server, a pxe profile will be generated

  configuration:
    keyboard_layout: us # us, fr, etc.
    system_language: en_US.UTF-8 # You should not update this if you want to google issues...

  hardware:
    cpu:
      architecture: x86_64

