---

- name: package <|> Install sudo
  ansible.builtin.package:
    name: sudo
    state: present

- name: sudoers <|> Add sudoers users and groups
  community.general.sudoers:
    commands: "{{ item.commands | default(omit, true) }}"
    group: "{{ item.group | default(omit, true) }}"
    host: "{{ item.host | default(omit, true) }}"
    name: "{{ item.name }}"
    noexec: "{{ item.noexec | default(omit, true) }}"
    nopassword: "{{ item.nopassword | default(omit, true) }}"
    runas: "{{ item.runas | default(omit, true) }}"
    setenv: "{{ item.setenv | default(omit, true) }}"
    state: "{{ item.state | default(omit, true) }}"
    sudoers_path: "{{ item.sudoers_path | default(omit, true) }}"
    user: "{{ item.user | default(omit, true) }}"
    validation: "{{ item.validation | default(omit, true) }}"
  loop: "{{ sudoers }}"
  when: sudoers is defined and sudoers | length > 0

- name: sudoers <|> Enable logging
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ item }}"
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - "Defaults   log_output"
    - "Defaults:{{ ansible_user }} !log_output"
  when: sudoers_logging | bool
