---
dns_server_dnssec_enable: yes
dns_server_dnssec_validation: yes
dns_server_dnssec_lookaside: auto

dns_server_forwarders: [] # list of custom forwarders ip.
dns_server_allow_query: [] # list with subnet/prefix format. Ex: - 10.10.0.0/16
