---
- name: "package <|> Install cloud-init"
  ansible.builtin.package:
    name: "cloud-init"
    state: present
  tags:
    - package

- name: "template <|> Generate /etc/cloud/cloud.cfg"
  ansible.builtin.template:
    src: cloud.cfg.j2
    dest: "/etc/cloud/cloud.cfg"
    owner: root
    group: root
    mode: 0644
  tags:
    - template

- name: "service <|> Manage {{ cloudinit_services_to_start | join(' ') }} state"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "{{ (cloudinit_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (cloudinit_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  loop: "{{ cloudinit_services_to_start }}"
  tags:
    - service

