---
- name: computes
  hosts: "{{ target }}"
  roles:

    - role: set_hostname
      tags: set_hostname
    - role: repositories_client
      tags: repositories_client
    - role: nic
      tags: nic
    - role: hosts_file
      tags: hosts_file
    - role: dns_client
      tags: dns_client
    - role: time
      tags: time
      vars:
        time_profile: client
    - role: nfs_client
      tags: nfs_client

