---
- name: "package <|> Install {{ slurm_packages_to_install['accounting'] | join(' ') }}"
  ansible.builtin.package:
    name: "{{ slurm_packages_to_install['accounting'] }}"
    state: present
  tags:
    - package

- name: "template <|> Generate {{ slurm_home_path }}/slurmdbd.conf"
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: "{{ slurm_home_path }}/slurmdbd.conf"
    owner: slurm
    group: slurm
    mode: 0600
  tags:
    - template

- name: "template <|> Generate /etc/my.cnf.d/slurmdbd.cnf"
  ansible.builtin.template:
    src: slurmdbd.cnf.j2
    dest: "{{ slurm_mysql_cnf_dir }}/slurmdbd.cnf"
    owner: root
    group: root
    mode: 0644
  tags:
    - template

- name: service <|> Manage mariadb state
  ansible.builtin.service:
    name: mariadb
    enabled: "{{ (slurm_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (slurm_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  tags:
    - service

- name: command <|> Check if slurm_acct_db database has been created
  ansible.builtin.command: mysql -e "SHOW DATABASES  LIKE 'slurm_acct_db'"
  register: slurm_database_exist
  changed_when: false
  tags:
    - service

- name: command <|> Check if slurm database user has been created
  ansible.builtin.command: mysql -e "use mysql; select Host,User from user;"
  register: slurm_database_user_exist
  changed_when: false
  tags:
    - service

- name: mysql_db <|> Create slurm_acct_db database
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: present
  when: "'slurm_acct_db' not in slurm_database_exist.stdout_lines"
  tags:
    - service

- name: setup slurm db user # noqa no-tabs
  community.mysql.mysql_user:
    name: "{{ slurm_storageuser }}"
    password: "{{ slurm_storagepass }}"
    priv: 'slurm_acct_db.*:ALL'
    state: present
  when: "('localhost\t' + slurm_storageuser) not in slurm_database_user_exist.stdout_lines"
  tags:
    - service

- name: service <|> Manage slurmdbd state
  ansible.builtin.service:
    name: slurmdbd
    enabled: "{{ (slurm_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (slurm_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  tags:
    - service

- name: "firewalld <|> Add Slurmdbd ports to firewall's {{ slurm_firewall_zone | default('public') }} zone"
  ansible.posix.firewalld:
    zone: "{{ slurm_firewall_zone | default('public') }}"
    port: "{{ slurm_slurmdbd_port }}/tcp"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  tags:
    - firewall
