---

- name: package <|> Install opensm packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - opensm
    - opensm-libs
  tags:
    - package

- name: service <|> Manage opensm state
  ansible.builtin.service:
    name: opensm
    enabled: "{{ (interconnect_enable_services | default(bb_enable_services) | default(true) | bool) | ternary('yes', 'no') }}"
    state: "{{ (interconnect_start_services | default(bb_start_services) | default(true) | bool) | ternary('started', omit) }}"
  tags:
    - service
