- name: "firewalld <|> Add services to firewall's {{ pxe_stack_firewall_zone | default('public') }} zone"
  ansible.posix.firewalld:
    zone: "{{ pxe_stack_firewall_zone | default('public') }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "Suse"
    - os_firewall | default(false) | bool
  loop: "{{ pxe_stack_firewall_services_to_add }}"
  tags:
    - firewall
