---
nic_reload_connections: false  # Reload network connections if changed
nic_force_nic_restart: false  # Force restart connection using down and up, could lose connectivity, beware
nic_restart_timeout: 2 # Time to wait before restarting connection using down and up
nic_force_reboot: false  # Reboot OS in case of NIC configuration change, can be useful if a gateway was updated
nic_allow_reboot: true  # Reboot after switch from netplan to network-manager on Ubuntu systems, or to enable NM on Suse.
nic_start_services: true
nic_reboot_timeout: 600
nic_nmcli_device_is_connection_name: true  # If true, the role will force existing connections to have the same name as their related device.
