---
- name: service â–ˆ Restart nfs server services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ nfs_server_services_to_start }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
