---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: management1
    groups:
      - mg_managements
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      management1:

        network_interfaces:
          - interface: enp0s3
            ip4: 10.11.0.1
            mac: 08:00:27:dc:f8:f5
            network: ice1-1

        start_services: false
        enable_services: true
        domain_name: tumulus.local
        icebergs_system: false
        j2_node_main_network: ice1-1
        j2_current_iceberg_network: ice1

        ep_firewall: true
        ep_equipment_type: server
        ep_ipxe_driver: snponly
        ep_ipxe_embed: standard
        ep_ipxe_platform: pcbios
        ep_hardware:
          cpu:
            architecture: x86_64

        networks:
          ice1-1:
            subnet: 10.11.0.0
            prefix: 16
            shared_network: wolf
            netmask: 255.255.0.0
            broadcast: 10.11.255.255
            gateway: 10.11.2.1
            is_in_dhcp: true
            is_in_dns: true
            services_ip:
              pxe_ip: 10.11.0.1
              dns_ip: 10.11.0.1
              repository_ip: 10.11.0.1
              authentication_ip: 10.11.0.1
              time_ip: 10.11.0.1
              log_ip: 10.11.0.1

          ice1-2:
            subnet: 10.30.0.0
            prefix: 16
            shared_network: wolf
            netmask: 255.255.0.0
            broadcast: 10.30.255.255
            dhcp_unknown_range: 10.30.0.2 10.30.0.254
            gateway: 10.30.2.1
            is_in_dhcp: true
            is_in_dns: true
            services_ip:
              pxe_ip: 10.30.0.1
              dns_ip: 10.30.0.1
              repository_ip: 10.30.0.1
              authentication_ip: 10.30.0.1
              time_ip: 10.30.0.1
              log_ip: 10.30.0.1

    hosts:
      fake_computes:
        hosts:

          compute1:
            network_interfaces:
              - interface: enp0s3
                ip4: 10.11.3.1
                mac: 08:00:27:dc:f8:f6
                network: ice1-1
            bmc:
              name: compute1-bmc
              ip4: 10.11.103.1
              mac: 08:00:27:dc:f8:f6
              network: ice1-1

            ep_ipxe_driver: default
            ep_ipxe_embed: standard
            ep_ipxe_platform: pcbios
            ep_hardware:
              cpu:
                architecture: x86_64

          compute2:
            alias:
              - compute2-opt82
            network_interfaces:
              - interface: enp0s3
                match: |
                  (substring (option agent.remote-id, 0 , 14) = "0"
                  and option agent.circuit-id = 01:00:16
                  and not (substring(option vendor-class-identifier, 0, 15) = "VENDOR_NAME_1" or
                  substring(option vendor-class-identifier, 0, 13) = "VENDOR_NAME_2")) or
                  (option dhcp-message-type = 3 and binary-to-ascii(10, 8, ".", option dhcp-requested-address) = "10.11.3.2" )
                ip4: 10.11.3.2
                network: ice1-1
            bmc:
              name: compute2-bmc
              alias:
                - compute2-opt82-bmc
              match: |
                substring (option agent.remote-id, 0 , 44) = "0"
                and option agent.circuit-id = 01:00:17
                and (substring(option vendor-class-identifier, 0, 10) = "VENDOR_NAME_1")
              ip4: 10.11.103.2
              network: ice1-1

            ep_ipxe_driver: default
            ep_ipxe_platform: efi
            ep_ipxe_embed: standard
            ep_hardware:
              cpu:
                architecture: x86_64

          compute3:
            alias:
              - compute3-opt61
            network_interfaces:
              - interface: enp0s3
                ip4: 10.30.3.3
                mac: 08:00:27:dc:f8:f7
                network: ice1-2
            bmc:
              name: compute3-bmc
              alias:
                - compute3-opt61-bmc
              dhcp_client_identifier: 00:30:18
              ip4: 10.30.103.3
              network: ice1-2

            ep_ipxe_driver: snponly
            ep_ipxe_platform: efi
            ep_ipxe_embed: standard
            ep_hardware:
              cpu:
                architecture: x86_64
verifier:
  name: ansible
