---
- name: service <|> Restart conman
  ansible.builtin.service:
    name: conman
    state: restarted
  when:
    - "'service' not in ansible_skip_tags"
    - conman_start_services | default(bb_start_services) | default(true) | bool

- name: systemd <|> Reload systemd configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - "'service' not in ansible_skip_tags"
