---
- name: command █ Reload connections
  command: nmcli con reload
  when: nic_nmcli_reload_connections

- name: command █ Netplan generate
  command: netplan generate

- name: command █ Netplan apply
  command: netplan apply

- name: reboot █ Reboot Ubuntu system to enable Network-Manager first time
  reboot:
    reboot_timeout: "{{ nic_nmcli_reboot_timeout }}"
  when:
    - nic_nmcli_allow_ubuntu_reboot
