equipment_profile:

  # iPXE network driver
  # default should be good for most of NIC, but some need SNP
  ipxe_network_driver: snp #default # default or snp or snponly

  # When installing in EFI, grub2 break the boot order and set next boot to disk (seriously, why??!)
  # In most case, you prefer system to continue to boot on PXE, and so the stack can restore first boot device after grub2 installation
  preserve_efi_first_boot_device: true # true or false

  console:
  kernel_parameters:

  access_control: true # Selinux, AppArmor, etc. Selinux: true = enforcing, false = disabled
  firewall: true # Enable or disable native firewall

  partitioning: | # Please provide native distribution partitioning. This example is for Centos/RedHat systems.
    clearpart --all --initlabel
    autopart --type=plain --fstype=ext4 --nohome

  operating_system:
    distribution: centos # centos, redhat, debian, ubuntu, opensuse, etc.
    distribution_major_version: 8
    distribution_version: 8.0

  equipment_type: none  # If server, a pxe profile will be generated

  configuration:
    keyboard_layout: us # us, fr, etc.
    system_language: en_US.UTF-8 # You should not update this if you want to google issues...

  hardware:
    cpu:
      architecture: x86_64
      cores: 1

  equipment_authentication: # login/password for BMC, storage bay controller, switch, etc.
    user: ADMIN
    password: ADMIN

