---

- name: service â–ˆ Restart rsyslog service
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ j2_role_variables['services_to_start'] }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
