---

- name: Package
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_to_install[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"

- name: Template >> /etc/dhcp/dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcp services
  tags:
    - template

- name: Template >> /etc/dhcp/dhcpd.networks.conf
  template:
    src: dhcpd.networks.conf.j2
    dest: /etc/dhcp/dhcpd.networks.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart dhcp services
  tags:
    - template

- name: Template >> /etc/dhcp/dhcpd.{{ item }}.conf
  template:
    src: dhcpd.subnet.conf.j2
    dest: /etc/dhcp/dhcpd.{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ networks }}"
  when:
    - j2_current_iceberg_network in item
    - networks[item].is_in_dhcp
  notify: Restart dhcp services
  tags:
    - template

- name: Manage services state
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  tags:
    - service
