---

- name: Package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - prometheus
    - alertmanager
    - ipmi_exporter

- name: Create directories structure
  file:
   path: "{{ item }}"
   state: directory
   mode: 0750
   owner: prometheus
   group: prometheus
  with_items:
   - /etc/prometheus/alerts/
   - /var/lib/prometheus

- name: Template >> /etc/prometheus/prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0640
  tags:
    - template

- name: Template >> /etc/prometheus/alerts/general.yml
  template:
    src: alerts/general.yml.j2
    dest: /etc/prometheus/alerts/general.yml
    owner: prometheus
    group: prometheus
    mode: 0640

- name: Template >> /etc/prometheus/alerts/bb_exporter.yml
  template:
    src: alerts/bb_exporter.yml.j2
    dest: /etc/prometheus/alerts/bb_exporter.yml
    owner: prometheus
    group: prometheus
    mode: 0640

#- name: Template >> /etc/prometheus/alerts/general.yml
#  copy:
#    src: alerts_general.yml
#    dest: /etc/prometheus/alerts/general.yml
#    owner: prometheus
#    group: prometheus
#    mode: 0640

- name: Create directories structure for alertmanager
  file:
   path: "{{ item }}"
   state: directory
   mode: 0750
   owner: alertmanager
   group: alertmanager
  with_items:
   - /etc/alertmanager

- name: Template >> /etc/alertmanager/alertmanager.yml
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: 0640
  tags:
    - template

- name: Template >> /etc/ipmi_exporter/ipmi_config.yml
  template:
    src: ipmi_config.yml.j2
    dest: /etc/ipmi_exporter/ipmi_config.yml
    owner: ipmiexporter
    group: ipmiexporter
    mode: 0640
  tags:
    - template

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - prometheus
    - alertmanager
    - ipmi_exporter
