---
pxe_stack_role_version: 1.2.0

pxe_stack_supported_os:
#  centos:
#    - 7
#    - 8
  redhat:
    - major: 7
      distributions:
        - redhat
        - centos
    - major: 8
      distributions:
        - redhat
        - centos
        - cloudlinux
        - oraclelinux
        - almalinux
        - rocky
    - major: 9
      distributions:
        - redhat
  ubuntu:
    - major: 18
      distributions:
        - ubuntu
