---
pxe_stack_apache_cgi_module: cgi
pxe_stack_apache_conf_path: /etc/httpd/conf.d
pxe_stack_apache_user: apache
pxe_stack_packages_to_install:
  - ipxe-x86_64-bluebanquise
  - ipxe-arm64-bluebanquise
  - httpd
  - policycoreutils-python
  - python36
  - python36-PyYAML
  - python36-clustershell
  - bootset
pxe_stack_default_tftp_package: atftp
pxe_stack_services_to_start:
  - httpd
pxe_stack_default_tftp_service: atftpd
pxe_stack_firewall_services_to_add:
  - http
  - tftp
pxe_stack_apache_cgi_bin_path: /var/www/cgi-bin
