---
pxe_stack_apache_cgi_module: cgi
pxe_stack_apache_conf_path: /etc/httpd/conf.d
pxe_stack_apache_user: apache
pxe_stack_packages_to_install:
  - atftp
  - ipxe-x86_64-bluebanquise
  - ipxe-arm64-bluebanquise
  - httpd
  - policycoreutils-python
  - python36
  - python36-PyYAML
  - python36-clustershell
pxe_stack_services_to_start:
  - atftpd
  - httpd
