---
pxe_stack_apache_cgi_module: cgid
pxe_stack_apache_conf_path: /etc/apache2/conf.d
pxe_stack_apache_user: wwwrun
pxe_stack_apache_cgi_bin_path: /srv/www/cgi-bin
pxe_stack_htdocs_path: /srv/www/htdocs/preboot_execution_environment
pxe_stack_packages_to_install:
  - apache2
  - autoyast2
  - autoyast2-installation
  - clustershell
  - libxml2-tools
  - ipxe-x86_64-bluebanquise
#  - ipxe-arm64-bluebanquise
  - python3-clustershell
pxe_stack_default_tftp_package: atftp
pxe_stack_services_to_start:
  - httpd
pxe_stack_default_tftp_service: atftpd.socket
pxe_stack_firewall_services_to_add:
  - http
  - tftp
