---
pxe_stack_apache_user: www-data
pxe_stack_apache_conf_path: /etc/apache2/conf-enabled
pxe_stack_apache_cgi_module: cgid
pxe_stack_packages_to_install:
  - bluebanquise-ipxe-x86-64
  - bluebanquise-ipxe-arm64
  - apache2
  - python3
  - python3-yaml
  - python3-clustershell
  - bluebanquise-bootset
pxe_stack_default_tftp_package: tftpd-hpa
pxe_stack_services_to_start:
  - apache2
pxe_stack_default_tftp_service: tftpd-hpa
pxe_stack_apache_cgi_bin_path: /usr/lib/cgi-bin
