---
- name: "package █ Install {{ j2_role_variables['packages_to_install'] | join(' ') }} packages"
  package:
    name: "{{ j2_role_variables['packages_to_install'] }}"
    state: present
  tags:
    - package

- name: group █ Ensure group conman exists
  group:
    name: conman
    state: present
    system: yes

- name: user █ Ensure user conman exists
  user:
    name: conman
    state: present
    comment: "Connection Manager service"
    group: conman
    home: /var/run/conman
    shell: /bin/false
    system: yes

- name: file █ Create /var/log/conman directory
  file: # noqa 208
    path: /var/log/conman
    setype: "{{ (ansible_facts.selinux.status == 'enabled') | ternary('conman_log_t', omit) }}"
    state: directory
    owner: conman
    group: conman
    recurse: yes
  notify: service █ Restart conman
  when:
    - ansible_facts.os_family == "RedHat"

- name: file █ Ensure systemd drop-in directory exists
  file:
    path: /etc/systemd/system/conman.service.d
    mode: 0755
    state: directory
    owner: root
    group: root
  when:
    - ansible_facts.os_family == "RedHat"

- name: copy █ Ensure service run with user conman
  copy:
    content: |
      [Service]
      User=conman
      Group=conman
      ExecStart=
      ExecStart=/usr/sbin/conmand -P /var/run/conman/conmand.pid
      PIDFile=/var/run/conman/conmand.pid
    dest: /etc/systemd/system/conman.service.d/user.conf
    mode: 0644
  notify: systemd █ Reload systemd configuration
  when:
    - ansible_facts.os_family == "RedHat"

- name: template █ Generate /etc/conman.conf
  template:
    src: conman.conf.j2
    dest: /etc/conman.conf
    owner: conman
    group: conman
    mode: 0600
  notify: service █ Restart conman
  tags:
    - template

- name: seboolean █ Allow all daemons the ability to use unallocated ttys
  seboolean:
    name: daemons_use_tty
    state: yes
    persistent: yes
  when:
    - ansible_facts.selinux.status == "enabled"

- meta: flush_handlers

- name: service █ Manage conman state
  service:
    name: conman
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
