---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: icebergs-off
    groups:
      - molecule_platform
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    pre_build_image: true
  - name: icebergs-on
    groups:
      - iceberg2
      - mg_managements
      - molecule_platform
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    pre_build_image: true
  - name: hostkey_checking
    groups:
      - molecule_platform
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      icebergs-off:
        icebergs_system: false
        j2_current_iceberg: iceberg1
        j2_current_iceberg_network: ice1
        network_interfaces:
          en0:
            network: ice1-1
      icebergs-on:
        icebergs_system: true
        iceberg_master: iceberg1
        j2_current_iceberg: iceberg2
        j2_current_iceberg_network: ice1
        managements_group_name: mg_managements
        network_interfaces:
          en0:
            network: ice1-1
      hostkey_checking:
        security:
          ssh:
            hostkey_checking: true
        icebergs_system: false
        j2_current_iceberg: iceberg1
        j2_current_iceberg_network: ice1
        network_interfaces:
          en0:
            network: ice1-1
    # Extra hosts
    hosts:
      iceberg2:
        hosts:
          fake-mgmt2:
            iceberg_master: iceberg1
            j2_current_iceberg_network: ice1
            network_interfaces:
              en0:
                network: ice1-1
      computes:
        hosts:
          fake-host1:
            j2_current_iceberg_network: ice1
            network_interfaces:
              en0:
                network: ice1-1
          fake-host2:
            j2_current_iceberg_network: ice1
            network_interfaces:
              en0:
                network: ice1-1
          fake-host3:
            j2_current_iceberg_network: ice1
            network_interfaces:
              en0:
                network: ice1-1
          fake-host4:
            j2_current_iceberg_network: ice1
            network_interfaces:
              en0:
                network: ice1-1
verifier:
  name: ansible
