---
- name: Prepare
  hosts: all
  tasks:
    - name: Install firewall package
      package:
        name: firewalld
        state: present

    - name: Start firewall 
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: Create /opt/software directory
      file:
        path: /opt/software
        state: directory
        mode: 0755
