---
- name: include_tasks ░ Setup Prometheus
  include_tasks: "server_prometheus.yml"
  when: prometheus_server_manage_prometheus
  tags:
    - internal

- name: include_tasks ░ Setup Alertmanager
  include_tasks: "server_alertmanager.yml"
  when: prometheus_server_manage_alertmanager
  tags:
    - internal

- name: include_tasks ░ Setup Karma
  include_tasks: "server_karma.yml"
  when: prometheus_server_manage_karma
  tags:
    - internal

#- name: include_tasks ░ Setup Am-executor
#  include_tasks: "server_am_executor.yml"
#  when: prometheus_server_manage_karma
#  tags:
#    - internal

- name: include_tasks ░ Setup ipmi_exporter
  include_tasks: "server_ipmi_exporter.yml"
  when: prometheus_server_manage_ipmi_exporter
  tags:
    - internal

- name: include_tasks ░ Setup snmp_exporter
  include_tasks: "server_snmp_exporter.yml"
  when: prometheus_server_manage_snmp_exporter
  tags:
    - internal

