---
- name: firewalld <|> "Add services to firewall's zone"
  ansible.posix.firewalld:
    zone: "{{ dns_server_firewall_zone | default(bb_services_firewall_zone, true) | default('public') }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - os_firewall | default(false) | bool
  loop: "{{ dns_server_firewall_services_to_add }}"
  tags:
    - firewall
