---
nic_role_version: 1.12.0

j2_nic_nmcli_device_name_type: "{%- set cons = [] -%}
{%- for device in (nmcli_con_show.stdout | split('\n')) -%}
  {%- if (device | split(':'))[0] != '' and (device | split(':'))[0] is not none -%}
    {%- set con = {'device': (device | split(':'))[0], 'name': (device | split(':'))[1], 'type': (device | split(':'))[2], 'apply': true} -%}
    {%- for interface in (network_interfaces | default([], true)) -%}
      {%- if interface.interface is defined and interface.interface == con.device and interface.nmcli_device_is_connection_name is defined and not (interface.nmcli_device_is_connection_name | default(true) | bool) -%}
        {%- set _ = con.update({'apply': False}) -%}
      {%- endif %}
    {%- endfor -%}
    {{ cons.append(con) }}
  {%- endif -%}
{%- endfor -%}
{{ cons }}"

nic_j2_ip4: "{{ nic_j2_ip4_main | trim }}{% if item.ip4 is defined and item.ip4_manual is defined %},{% endif %}{{ nic_j2_ip4_manual | trim }}"

nic_j2_ip4_main: "
{% if item.ip4 is defined %}
  {% if '/' in item.ip4 %}
    {{ item.ip4 }}
  {% elif item.network is defined and networks[item.network]['prefix4'] is defined %}
    {{ item.ip4 }}/{{ networks[item.network]['prefix4'] }}
  {% elif item.network is defined and networks[item.network]['prefix'] is defined %}
    {{ item.ip4 }}/{{ networks[item.network]['prefix'] }}
  {% endif %}
{% endif %}
"

nic_j2_ip4_manual: "
{% if item.ip4_manual is defined %}
  {% for ipsub in item.ip4_manual %}{% if not loop.first %},{% endif %}{{ ipsub }}{%endfor %}
{% endif %}
"

nic_j2_ip6: "
{% if item.ip6 is defined %}
  {% if '/' in item.ip6 %}
    {{ item.ip6 }}
  {% elif item.network is defined and networks[item.network]['prefix6'] is defined %}
    {{ item.ip6 }}/{{ networks[item.network]['prefix6'] }}
  {% endif %}
{% endif %}
"

# Check here if never_default4 is set or not. If set, gw4 cannot be used as both are mutually exclusive. If not set, then get gw4 from network_interfaces, then default to network.gateway4 then default to network.gateway then omit.
nic_j2_gw4: "
{% if item.never_default4 is not defined %}
  {% if item.gw4 is defined %}
    {{ item.gw4 }}
  {% elif item.network is defined and networks[item.network]['gateway4'] is defined %}
    {% if networks[item.network]['gateway4'] is string %}
      {{ networks[item.network]['gateway4'] }}
    {% elif networks[item.network]['gateway4'] is iterable and networks[item.network]['gateway4'] is not mapping %}
      {% if networks[item.network]['gateway4'][0]['ip'] is defined %}
        {{ networks[item.network]['gateway4'][0]['ip'] }}
      {% elif networks[item.network]['gateway4'][0]['hostname'] is defined %}
        {{ networks[item.network]['gateway4'][0]['hostname'] }}
      {% endif %}
    {% endif %}
  {% elif item.network is defined and networks[item.network]['gateway'] is defined %}
    {{ networks[item.network]['gateway'] }}
  {% endif %}
{% endif %}
"

nic_j2_gw6: "
{% if item.never_default6 is not defined %}
  {% if item.gw6 is defined %}
    {{ item.gw6 }}
  {% elif item.network is defined and networks[item.network]['gateway6'] is defined %}
    {{ networks[item.network]['gateway6'] }}
  {% endif %}
{% endif %}
"

nic_j2_routes4: "
{% if item.routes4 is defined %}
  {{ item.routes4 }}
{% elif item.network is defined and networks[item.network]['routes4'] is defined %}
  {{ networks[item.network]['routes4'] }}
{% endif %}
"

nic_j2_route_metric4: "
{% if item.route_metric4 is defined %}
  {{ item.route_metric4 }}
{% elif item.network is defined and networks[item.network]['route_metric4'] is defined %}
  {{ networks[item.network]['route_metric4'] }}
{% endif %}
"

nic_j2_never_default4: "
{% if item.never_default4 is defined %}
  {{ item.never_default4 }}
{% elif item.network is defined and networks[item.network]['never_default4'] is defined %}
  {{ networks[item.network]['never_default4'] }}
{% endif %}
"

nic_j2_mtu: "
{% if item.mtu is defined %}
  {{ item.mtu }}
{% elif item.network is defined and networks[item.network]['mtu'] is defined %}
  {{ networks[item.network]['mtu'] }}
{% endif %}
"

nic_j2_dns4: "
{% if item.dns4 is defined %}
  {{ item.dns4 }}
{% elif item.network is defined and networks[item.network]['dns4'] is defined %}
  {{ networks[item.network]['dns4'] }}
{% elif item.network is defined and networks[item.network]['services'] is defined and networks[item.network]['services']['dns4'] is defined %}
  {{ networks[item.network]['services']['dns4'][0]['ip4'] }}
{% elif item.network is defined and networks[item.network]['services'] is defined and networks[item.network]['services']['dns'] is defined %}
  {{ networks[item.network]['services']['dns'][0]['ip4'] }}
 {% elif item.network is defined and networks[item.network]['services_ip'] is defined %}
  {{ networks[item.network]['services_ip'] }}
{% endif %}
"

nic_j2_dns4_search: "
{% if item.dns4_search is defined %}
  {{ item.dns4_search }}
{% elif item.network is defined and networks[item.network]['dns4_search'] is defined %}
  {{ networks[item.network]['dns4_search'] }}
{% endif %}
"
