---
prometheus_server_prometheus_packages_to_install:
  - prometheus
prometheus_server_alertmanager_packages_to_install:
  - alertmanager
prometheus_server_ipmi_exporter_packages_to_install:
    - ipmi_exporter
    - freeipmi
prometheus_server_snmp_exporter_packages_to_install:
  - snmp_exporter
prometheus_server_snmp_exporter_additional_packages_to_install:
  - gcc
  - make
  - net-snmp
  - net-snmp-utils
  - net-snmp-libs
  - net-snmp-devel
prometheus_server_karma_packages_to_install:
  - karma
