---

- name: Restart rsyslog services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
