---

- name: Restart pxe services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  when: (start_services | bool)
  tags:
    - service
