---
- name: service █ Restart pxe services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ pxe_stack_services_to_start }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)

- name: systemd █ Reload systemd configuration
  systemd:
    daemon_reload: yes
