---
### Lease times ###
# Consider increasing these values once cluster is in production.
dhcp_server_default_lease_time: 600
dhcp_server_max_lease_time: 7200

### iPXE Rom settings ###
# These default should suits most hardware.
# Refer to main documentation for possible values.
# It is possible using these settings to bind to an non BlueBanquise iPXE Rom.
dhcp_server_ipxe_driver: snponly
dhcp_server_ipxe_embed: standard

### Enable and/or start services ###
# These values can be set in inventory to manipulate
# services behavior. If not set, default to true for both.
# Roles variables precedence global ones:
# dhcp_server_start_services > bb_start_services > default(true)
# dhcp_server_enable_services > bb_enable_services > default(true)
dhcp_server_start_services:
dhcp_server_enable_services:

### Others ###
# Domain name provided by dhcp to clients
dhcp_server_domain_name: cluster.local

