---
- name: service <|> Restart firewall services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ firewall_services_to_start }}"
  when:
    - "'service' not in ansible_skip_tags"
    - (start_services | bool)
