---
pxe_stack_apache_cgi_module: cgi
pxe_stack_apache_conf_path: /etc/httpd/conf.d
pxe_stack_apache_user: apache
pxe_stack_apache_group: apache
pxe_stack_htdocs_path: /var/www/html
pxe_stack_packages_to_install:
  - bluebanquise-ipxe-x86_64
  - bluebanquise-ipxe-arm64
  - httpd
  - policycoreutils-python
  - clustershell
  - python36
  - python36-PyYAML
pxe_stack_default_tftp_package: atftp
pxe_stack_services_to_start:
  - httpd
pxe_stack_default_tftp_service: atftpd
pxe_stack_firewall_services_to_add:
  - http
  - tftp
pxe_stack_apache_cgi_bin_path: /var/www/cgi-bin
pxe_stack_diskless_packages_to_install:
  - nfs-utils
  - libselinux-python
  - policycoreutils-python
pxe_stack_diskless_services_to_start:
  - nfs-server
  - rpcbind
pxe_stack_diskless_firewall_services_to_add:
  - nfs
  - rpc-bind
  - mountd
