---
pxe_stack_apache_cgi_module: cgid
pxe_stack_apache_conf_path: /etc/httpd/conf.d
pxe_stack_apache_user: apache
pxe_stack_apache_group: apache
pxe_stack_htdocs_path: /var/www/html
pxe_stack_packages_to_install:
  - bluebanquise-ipxe-x86_64
  - bluebanquise-ipxe-arm64
  - httpd
  - python3-policycoreutils
  - python3-pyyaml
  - policycoreutils
pxe_stack_default_tftp_package: bluebanquise-atftp
pxe_stack_services_to_start:
  - httpd
pxe_stack_default_tftp_service: tftp
pxe_stack_firewall_services_to_add:
  - http
  - tftp
pxe_stack_apache_cgi_bin_path: /var/www/cgi-bin
pxe_stack_diskless_packages_to_install:
  - nfs-utils
  - python3-libselinux
  - python3-policycoreutils
pxe_stack_diskless_services_to_start:
  - nfs-server
  - rpcbind
pxe_stack_diskless_firewall_services_to_add:
  - nfs
  - rpc-bind
  - mountd
