---
- name: authorized_key â–ˆ Add authorized key
  ansible.posix.authorized_key:
    user: "{% if ansible_env.SUDO_USER is defined %}{{ ansible_env.SUDO_USER }}{% else %}root{% endif %}"
    key: "{{ item }}"
    exclusive: no
    state: present
  with_items: "{{ authentication_ssh_keys }}"
