---
dns_server_dnssec_enable: true
dns_server_dnssec_validation: auto
dns_server_dnssec_lookaside: auto
dns_server_dnssec_overwrite_key: false # Overwrite existing keys
dns_server_enable_dnssec: false # Create and sign zones

dns_server_recursion: false  # Enable recursion, to be combined with forwarders

dns_server_forwarders: []  # list of custom forwarders ip.
dns_server_listen_on_ip4: []  # List of custom listen ipv4. Ex: - 10.10.0.1
dns_server_allow_query: []  # list with subnet/prefix format. Ex: - 10.10.0.0/16

dns_server_domain_name:

# Allow to write all host names
# If set to true, hostname, alias, nic-network and nic-alias will be written info forward files
# If set to false, only hostname and alias will be written into forward files
dns_server_enable_extended_names: true

# dns_server_overrides
# dns_server_start_services:
# dns_server_enable_services:
