---
- name: toto
  hosts: "management1"
  roles:
    - role: report
      tags: report

    - role: ssh_slave
      tags: ssh_slave
    - role: ssh_master
      tags: ssh_master

    - role: users_basic
      tags: users_basic

    - role: log_server
      tags: log_server
    - role: clustershell
      tags: clustershell

    - role: openldap_server
      tags: openldap_server
    - role: openldap_client
      tags: openldap_client
    - role: set_hostname
      tags: set_hostname
    - role: repositories_server
      tags: repositories_server
    - role: repositories_client
      tags: repositories_client
    - role: pxe_stack
      tags: pxe_stack
    - role: nic
      tags: nic
    - role: hosts_file
      tags: hosts_file
    - role: dhcp_server
      tags: dhcp_server
    - role: dns_server
      tags: dns_server
    - role: dns_client
      tags: dns_client
    - role: time_server
      tags: time_server
    - role: nfs_server
      tags: nfs_server
    - role: nfs_client
      tags: nfs_client
    - role: HPC_slurm
      tags: HPC_slurm
      vars:
        slurm_profile: controler
    - role: prometheus_server
      tags: prometheus_server
