---
- name: firewalld █ "Add services to firewall's {{ dns_server_firewall_zone | default('public',true) }} zone"
  firewalld:
    zone: "{{ dns_server_firewall_zone | default('public',true) }}"
    service: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
    state: enabled
  when:
    - ansible_facts.os_family == "RedHat"
    - ep_firewall | default(false) | bool
  loop: "{{ j2_role_variables['firewall_services_to_add'] }}"
  tags:
    - firewall

- name: "package █ Install {{ j2_role_variables['packages_to_install'] | join(' ') }} packages"
  package:
    name: "{{ j2_role_variables['packages_to_install'] }}"
    state: present
  tags:
    - package

- name: file █ Create needed directory /var/named
  file:
    path: /var/named
    state: directory
    mode: 0755

- name: template █ Generate /etc/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart dns services
  tags:
    - template

- name: template █ Generate Forward zone file on Master DNS /var/named/forward
  template:
    src: forward.j2
    dest: /var/named/forward
    owner: root
    group: root
    mode: 0644
  register: zoneconf
  tags:
    - template

- name: set_fact ░ Set SOA Serial for reverse zone
  set_fact:
    serial: "{{ lookup('pipe', 'date +%s') }}"
  when: zoneconf.changed  # noqa 503
  tags:
    - template
    - internal

- name: template █ Generate SOA for forward zone file /var/named/forward.soa
  template:
    src: forward.soa.j2
    dest: /var/named/forward.soa
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart dns services
  when: zoneconf.changed  # noqa 503
  tags:
    - template

- name: template █ Generate Reverse zone file on Master DNS /var/named/reverse
  template:
    src: reverse.j2
    dest: /var/named/reverse
    owner: root
    group: root
    mode: 0644
  tags:
    - template

- name: template █ Generate SOA for reverse zone file /var/named/reverse.soa
  template:
    src: reverse.soa.j2
    dest: /var/named/reverse.soa
    owner: root
    group: root
    mode: 0644
  notify: service █ Restart dns services
  when: zoneconf.changed  # noqa 503
  tags:
    - template

- name: meta █ Run handler tasks to restart dns services
  meta: flush_handlers

- name: "service █ Manage {{ j2_role_variables['services_to_start'] | join(' ') }} state"
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ j2_role_variables['services_to_start'] }}"
  tags:
    - service
