---

- name: user <|> Add dhcpd user if missing
  ansible.builtin.user:
    name: dhcpd
    comment: DHCP server daemon
    home: /var/lib/dhcp
    shell: /bin/false
    group: nogroup
    system: true

- name: template <|> Generate /etc/sysconfig/dhcpd for SuSE based systems
  template:
    src: Suse/sysconfig.j2
    dest: /etc/sysconfig/dhcpd
    owner: root
    group: root
    mode: 0644
  notify: service <|> Restart dhcp server
  tags:
    - template
