---
name: core/ssh_master unit testing
on:
  push:
    branches:
      - master
    paths:
      - 'roles/core/ssh_master/**'
      - '.github/workflows/molecule-actions-core-ssh_master.yml'
  pull_request:
    paths:
      - 'roles/core/ssh_master/**'
      - '.github/workflows/molecule-actions-core-ssh_master.yml'

jobs:
  molecule_test:
    name: ${{ matrix.distro }} - molecule test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos:7
          - centos:8
          - opensuseleap:15.1

    env:
      MOLECULE_DISTRO: ${{ matrix.distro }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v1
      - name: Install packages
        run: |
          pip install 'molecule[docker]>3' ansible-lint flake8
      - name: Run molecule test for core/ssh_master
        run: |
          cd roles/core/ssh_master && molecule test
