---
name: Unit testing - Roles
on:
  push:
    branches:
      - master
    paths:
      - 'roles/**'
      - '.github/workflows/molecule-actions.yml'
  pull_request:
    paths:
      - 'roles/**'
      - '.github/workflows/molecule-actions.yml'

jobs:
  molecule_test:
    name: ${{ matrix.role }} - ${{ matrix.distro }} - molecule test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos8
        role:
          - core/conman
          - core/display_tuning
          - core/dns_client
          - core/dns_server
          - core/log_client
          - core/log_server
          - core/repositories_client
          - core/time
          - addons/clustershell
          - addons/users_basic

    env:
      MOLECULE_DISTRO: ${{ matrix.distro }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v1
      - name: Install packages
        run: |
          pip install 'molecule[docker]>3' ansible-lint flake8
      - name: Run molecule test for ${{ matrix.role }}
        run: |
          cd roles/${{ matrix.role }} && molecule test
