name: Static code analysis
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  check:
    name: Run static code analysis tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v1

      - name: Install packages
        run: pip install ansible ansible-lint flake8 yamllint

      - name: Check python code
        run: flake8 . --statistics --ignore E501,E226

      - name: Run ansible linter
        run: ansible-lint
        env:
          # Set path to ansible roles to workaround ansible-lint#1375
          ANSIBLE_ROLES_PATH: roles/core:roles/advanced_core
